 ## Srivathsan B   -  E22034


# Experiment 4:

AIM : 
#### Use cars.csv with variables  MPG as Dependent variable and HP,WT,CYL,DISP as Independent Variable 
#### Draw 200 random samples of size 80
#### For each random sample 
            i. Fit a KNN Model
            ii.KNN Model with knn as 2
            iii.KNN Model with knn as 10
            iii.Make predictions for a fixed test input 
            iv. Study the variance of the output
            v. Conclude which one has a high variance model.

In [1]:
# Importing the dependencies 

import pandas as pd
import numpy as np
import random
from sklearn.neighbors import KNeighborsRegressor

In [2]:
# mounting the drive 

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# reading the data from the google drive and reading as pandas dataset.

df = pd.read_csv('/content/drive/MyDrive/AML /cars.csv')
df.head() # Shows the first 5 rows of the dataset variable name df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130,3504,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165,3693,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150,3436,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150,3433,12.0,70,US
4,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US

In [4]:
# Droping Variables which is not required for the experiment.
df = df.drop(["Car",'Acceleration','Model','Origin'], axis = True)

In [5]:
# Seperating the independent and dependent variables 
X = df.drop(['MPG'], axis = 1 ) # All X's values 
y = df.MPG # y - values

# Taking 200 random samples with 80 observations and fitting a KNN model with k nearest neibghours as 2 and making predictions for fixed test input.

In [8]:
# Modeling the KNN Regressor 

predicted_knn_2 = [] # Initializing a empty list.


for i in range (1,201): # initiating a loop for 200 times.
    
    test = X.sample(1,random_state = 123) # taking a fixed sample.
    train_X = X.sample(80) # Taking 80 observations for train in X.
    train_y = y.sample(80) # Taking 80 observations for test data in y.
    
    # Step-1: instantiate learning model.
    knn = KNeighborsRegressor(n_neighbors=2, metric='euclidean')  # Fitting  a KNN Model with knn as 2

    # Step-2: fitting the model.
    knn.fit(train_X, train_y)

    # Step-3: Predicting the values.
    predicted_values_2 = knn.predict(test) # Making predictions for a fixed test input.
    predicted_knn_2.append(predicted_values_2) # Appending the predictions into predicted_knn_2 list.

np.var(predicted_knn_2) # Calculating  the variance of the output for the KNN Model.

34.02408975

# Taking 200 random samples with 80 observations and fitting a KNN model with k nearest neibghours as 10 and making predictions for fixed test input.

In [9]:
# Modeling the KNN Regressor 

predicted_knn_10 = [] # Initializing a empty list.


for i in range (1,201): # initiating a loop for 200 times.
    
    test = X.sample(1,random_state = 123) # taking a fixed sample.
    train_X = X.sample(80) # Taking 80 observations for train in X.
    train_y = y.sample(80) # Taking 80 observations for test data in y.
    
    # Step-1: instantiate learning model.
    knn = KNeighborsRegressor(n_neighbors=10, metric='euclidean')  # Fitting  a KNN Model with knn as 10

    # Step-2: fitting the model.
    knn.fit(train_X, train_y)

    # Step-3: Predicting the values.
    predicted_values_10 = knn.predict(test) # Making predictions for a fixed test input.
    predicted_knn_10.append(predicted_values_10) # Appending the predictions into predicted_knn_10 list.

np.var(predicted_knn_10) # Calculating  the variance of the output for the KNN Model.

6.177320197499999

## **Conclusion : **
*Experiment 4 Concludes that, in comparing the KNN models with K Nearest neighbours as 2 and 10 we fount out that KNN with 10 shows less variance*